---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.7.3"
  - PUPPET_VERSION="~> 3.7.3" PARSER=future
  - PUPPET_VERSION="~> 3.8.2" PARSER=future
  - PUPPET_VERSION="~> 4.0.0"
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.0"
